# Generated by Django 5.1.15 on 2026-09-12 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layers', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='projects.project'),
        ),
        migrations.AddField(
            model_name='feature',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feature',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='layers.dataset'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='layers.feature'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['company', 'project'], name='layers_data_company_87541e_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['dataset'], name='layers_feat_dataset_08524d_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['dataset', 'created_at'], name='layers_feat_dataset_5b67d5_idx'),
        ),
    ]
