# Generated by Django 5.1.15 on 2026-09-13

import hashlib
import secrets
import time

from django.db import migrations, models


def backfill_org_id(apps, schema_editor):
    Company = apps.get_model("accounts", "Company")

    def _generate():
        used = set(Company.objects.exclude(org_id="").values_list("org_id", flat=True))
        while True:
            raw = f"{secrets.token_hex(16)}-{time.time_ns()}"
            digest = int(hashlib.sha256(raw.encode("utf-8")).hexdigest(), 16)
            candidate = f"{digest % 10**10:010d}"
            if candidate not in used:
                used.add(candidate)
                return candidate

    for company in Company.objects.filter(org_id=""):
        company.org_id = _generate()
        company.save(update_fields=["org_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="org_id",
            field=models.CharField(editable=False, max_length=10, default=""),
        ),
        migrations.RunPython(backfill_org_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="company",
            name="org_id",
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="code",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]